package football.evolution;

import org.graphstream.graph.*;
import org.graphstream.graph.implementations.*;
import org.graphstream.ui.view.*;
import org.graphstream.ui.swing_viewer.*;
import org.graphstream.ui.layout.springbox.implementations.SpringBox;

import java.io.*;
import java.util.*;
import java.awt.Color;

/**
 * Football Teams Evolution - GraphStream Visualization
 * 
 * This class reads the graph data generated by Python and visualizes it
 * using GraphStream library.
 * 
 * Requirements:
 * - GraphStream Core: gs-core-2.0.jar
 * - GraphStream UI Swing: gs-ui-swing-2.0.jar
 * 
 * Maven dependencies:
 * <dependency>
 *     <groupId>org.graphstream</groupId>
 *     <artifactId>gs-core</artifactId>
 *     <version>2.0</version>
 * </dependency>
 * <dependency>
 *     <groupId>org.graphstream</groupId>
 *     <artifactId>gs-ui-swing</artifactId>
 *     <version>2.0</version>
 * </dependency>
 */
public class FootballGraphViewer {
    
    private Graph graph;
    private Map<String, Map<String, Object>> nodeAttributes;
    private String currentTeam;
    private int currentYear;
    
    // CSS styling for the graph
    private static final String GRAPH_STYLE = 
        "graph { padding: 50px; }" +
        "node { " +
        "   fill-color: #4285f4; " +
        "   size: 20px; " +
        "   text-size: 12; " +
        "   text-alignment: above; " +
        "   stroke-mode: plain; " +
        "   stroke-color: #1a53a5; " +
        "   stroke-width: 2px; " +
        "}" +
        "node.goalkeeper { fill-color: #ffc107; }" +
        "node.defender { fill-color: #28a745; }" +
        "node.midfielder { fill-color: #4285f4; }" +
        "node.forward { fill-color: #dc3545; }" +
        "node.selected { fill-color: #ff5722; size: 30px; }" +
        "edge { " +
        "   fill-color: #999999; " +
        "   arrow-size: 0; " +
        "}" +
        "edge.strong { fill-color: #333333; size: 3px; }" +
        "edge.medium { fill-color: #666666; size: 2px; }" +
        "edge.weak { fill-color: #cccccc; size: 1px; }";
    
    public FootballGraphViewer() {
        System.setProperty("org.graphstream.ui", "swing");
        this.nodeAttributes = new HashMap<>();
    }
    
    /**
     * Load graph from edge list file
     * Format: year\tplayer1\tplayer2\tweight\tteam
     */
    public void loadFromEdgeList(String filename) throws IOException {
        graph = new SingleGraph("Football Network");
        graph.setAttribute("ui.stylesheet", GRAPH_STYLE);
        graph.setAttribute("ui.quality");
        graph.setAttribute("ui.antialias");
        
        try (BufferedReader reader = new BufferedReader(new FileReader(filename))) {
            String line;
            int edgeCount = 0;
            
            while ((line = reader.readLine()) != null) {
                if (line.startsWith("#") || line.trim().isEmpty()) continue;
                
                String[] parts = line.split("\t");
                if (parts.length < 4) continue;
                
                int year = Integer.parseInt(parts[0]);
                String player1 = parts[1];
                String player2 = parts[2];
                int weight = Integer.parseInt(parts[3]);
                String team = parts.length > 4 ? parts[4] : "Unknown";
                
                // Add nodes if they don't exist
                addNode(player1, team);
                addNode(player2, team);
                
                // Add edge
                String edgeId = player1 + "_" + player2 + "_" + year;
                if (graph.getEdge(edgeId) == null) {
                    Edge edge = graph.addEdge(edgeId, player1, player2);
                    edge.setAttribute("weight", weight);
                    edge.setAttribute("year", year);
                    edge.setAttribute("team", team);
                    
                    // Style based on weight
                    if (weight >= 5) {
                        edge.setAttribute("ui.class", "strong");
                    } else if (weight >= 3) {
                        edge.setAttribute("ui.class", "medium");
                    } else {
                        edge.setAttribute("ui.class", "weak");
                    }
                    
                    edgeCount++;
                }
            }
            
            System.out.println("Loaded " + graph.getNodeCount() + " nodes and " + 
                             edgeCount + " edges");
        }
    }
    
    /**
     * Load graph from team-specific file
     */
    public void loadTeamGraph(String filename, String teamName) throws IOException {
        this.currentTeam = teamName;
        graph = new SingleGraph("Football Network - " + teamName);
        graph.setAttribute("ui.stylesheet", GRAPH_STYLE);
        graph.setAttribute("ui.quality");
        graph.setAttribute("ui.antialias");
        
        try (BufferedReader reader = new BufferedReader(new FileReader(filename))) {
            String line;
            int edgeCount = 0;
            
            while ((line = reader.readLine()) != null) {
                if (line.startsWith("#") || line.trim().isEmpty()) continue;
                
                String[] parts = line.split("\t");
                if (parts.length < 3) continue;
                
                String player1 = parts[0];
                String player2 = parts[1];
                int weight = Integer.parseInt(parts[2]);
                
                // Add nodes
                addNode(player1, teamName);
                addNode(player2, teamName);
                
                // Add edge
                String edgeId = "e" + edgeCount;
                Edge edge = graph.addEdge(edgeId, player1, player2);
                edge.setAttribute("weight", weight);
                
                // Style based on weight
                if (weight >= 5) {
                    edge.setAttribute("ui.class", "strong");
                } else if (weight >= 3) {
                    edge.setAttribute("ui.class", "medium");
                } else {
                    edge.setAttribute("ui.class", "weak");
                }
                
                edgeCount++;
            }
            
            System.out.println("Loaded " + teamName + ": " + 
                             graph.getNodeCount() + " players, " + 
                             edgeCount + " connections");
        }
    }
    
    /**
     * Load graph from DGS file (GraphStream native format)
     */
    public void loadFromDGS(String filename) throws IOException {
        graph = new SingleGraph("Football Network");
        graph.setAttribute("ui.stylesheet", GRAPH_STYLE);
        
        try {
            graph.read(filename);
            System.out.println("Loaded DGS file: " + graph.getNodeCount() + 
                             " nodes, " + graph.getEdgeCount() + " edges");
        } catch (Exception e) {
            System.err.println("Error loading DGS file: " + e.getMessage());
            throw new IOException(e);
        }
    }
    
    private void addNode(String playerId, String team) {
        if (graph.getNode(playerId) == null) {
            Node node = graph.addNode(playerId);
            node.setAttribute("ui.label", getShortName(playerId));
            node.setAttribute("team", team);
        }
    }
    
    private String getShortName(String fullName) {
        String[] parts = fullName.split(" ");
        if (parts.length > 1) {
            return parts[parts.length - 1]; // Last name
        }
        return fullName;
    }
    
    /**
     * Display the graph with interactive viewer
     */
    public void display() {
        Viewer viewer = graph.display();
        viewer.enableAutoLayout();
        
        // Add click listener
        ViewerPipe fromViewer = viewer.newViewerPipe();
        fromViewer.addViewerListener(new ViewerListener() {
            @Override
            public void viewClosed(String viewName) {}
            
            @Override
            public void buttonPushed(String id) {
                Node node = graph.getNode(id);
                if (node != null) {
                    System.out.println("\nPlayer: " + id);
                    System.out.println("Connections: " + node.getDegree());
                    node.setAttribute("ui.class", "selected");
                }
            }
            
            @Override
            public void buttonReleased(String id) {
                Node node = graph.getNode(id);
                if (node != null) {
                    node.removeAttribute("ui.class");
                }
            }
            
            @Override
            public void mouseOver(String id) {}
            
            @Override
            public void mouseLeft(String id) {}
        });
        
        // Pump events
        new Thread(() -> {
            while (true) {
                fromViewer.pump();
                try { Thread.sleep(50); } catch (InterruptedException e) { break; }
            }
        }).start();
    }
    
    /**
     * Apply spring layout algorithm
     */
    public void applySpringLayout() {
        SpringBox layout = new SpringBox(false);
        graph.setAttribute("layout.algorithm", layout);
        layout.compute();
    }
    
    /**
     * Filter graph to show only a specific year
     */
    public void filterByYear(int year) {
        this.currentYear = year;
        
        for (Edge edge : graph.edges().toArray(Edge[]::new)) {
            Integer edgeYear = (Integer) edge.getAttribute("year");
            if (edgeYear != null && edgeYear != year) {
                edge.setAttribute("ui.hide");
            } else {
                edge.removeAttribute("ui.hide");
            }
        }
        
        System.out.println("Filtered to year: " + year);
    }
    
    /**
     * Show statistics about the current graph
     */
    public void printStatistics() {
        System.out.println("\n=== Graph Statistics ===");
        System.out.println("Nodes (Players): " + graph.getNodeCount());
        System.out.println("Edges (Connections): " + graph.getEdgeCount());
        
        // Find most connected players
        List<Node> nodes = new ArrayList<>();
        graph.nodes().forEach(nodes::add);
        nodes.sort((a, b) -> b.getDegree() - a.getDegree());
        
        System.out.println("\nTop 10 Most Connected Players:");
        for (int i = 0; i < Math.min(10, nodes.size()); i++) {
            Node node = nodes.get(i);
            System.out.printf("  %d. %s (%d connections)%n", 
                            i + 1, node.getId(), node.getDegree());
        }
        
        // Calculate average degree
        double avgDegree = nodes.stream()
                                .mapToInt(Node::getDegree)
                                .average()
                                .orElse(0);
        System.out.printf("\nAverage connections per player: %.2f%n", avgDegree);
    }
    
    /**
     * Export graph to image file
     */
    public void exportToImage(String filename) {
        graph.setAttribute("ui.screenshot", filename);
        System.out.println("Graph exported to: " + filename);
    }
    
    /**
     * Main method - example usage
     */
    public static void main(String[] args) {
        FootballGraphViewer viewer = new FootballGraphViewer();
        
        String dataDir = "output";
        String graphDir = "graphs";
        
        try {
            // Load from edge list
            if (args.length > 0) {
                viewer.loadFromEdgeList(args[0]);
            } else if (new File(dataDir + "/player_edges.txt").exists()) {
                viewer.loadFromEdgeList(dataDir + "/player_edges.txt");
            } else if (new File(graphDir + "/graph_Liverpool.txt").exists()) {
                viewer.loadTeamGraph(graphDir + "/graph_Liverpool.txt", "Liverpool");
            } else {
                System.out.println("Usage: java FootballGraphViewer <edge_list_file>");
                System.out.println("\nOr place player_edges.txt in the output/ directory");
                System.out.println("\nRun the Python script first to generate data:");
                System.out.println("  python main.py --mode demo");
                return;
            }
            
            viewer.printStatistics();
            viewer.display();
            
        } catch (IOException e) {
            System.err.println("Error loading graph: " + e.getMessage());
            e.printStackTrace();
        }
    }
}
